### ISSUE TITLE
Using unsecure connection in browser

### ISSUE THREAD

**Issue by hbenkel** [vogler75/winccua-mqtt-client#1]
Hi Andreas, about the MQTT CWC in TIA Portal:

The server is the AEDES MQTT Broker in Node-Red.
The URL is ws://192.168.4.52:8083/ and works fine with the MQTT Explorer (Thomas Nordquist)
I dont use SSL
No script errors
TIA v19 Upd 2

Thanks in advanced

**Comment by vogler75** [comment]
Try to add /mqtt at ws://192.168.4.52:8083/mqtt at the end - just to be sure.

Enable the „Debug“ Flag in the CWC. Then open again the browser console before you open the screen with the CWC. You should see log messages if it can connect or not or errors..

**Comment by hbenkel** [comment]
Thanks for the feedback Andreas.
It seems to be a security issue. This is the error console, please see the attached file
![chrome_error_console](https://github.com/vogler75/winccua-mqtt-client/assets/88405624/a916c74f-5d23-4511-966f-fe11c3889fa6)

**Comment by vogler75** [comment]
You are right, the requests are blocked by your browser. You can allow insecure content in your browser when you click on the page settings in your browser (depends on your browser). Or you can use wss instead of ws - if your MQTT broker has wss enabled.

**Comment by hbenkel** [comment]
Exactly, modifying the browser configuration the connection is established.
Thanks a lot for your help Andreas.
Regards

**Comment by vogler75** [comment]
great! you are welcome.
